### ISSUE TITLE
Emulator's images disappear in the presence of an "images" controller and resourceful route

### ISSUE THREAD

**Issue by carelvwyk** [linsen/mxit-rails#16]
I have a controller named "images_controller". When I add the following route, the mxit-rails emulator can no longer serve images:

``` ruby
resources :images
```

My controller is named "images" for compatible reasons with another API.

**Comment by drubin** [comment]
I fixed in the the branch image-correction give it a try see if it works in your rails code. 

```
  gem "mxit-rails", :git => "git://github.com/linsen/mxit-rails.git", :branch => "image-correction"
```

**Comment by carelvwyk** [comment]
It's solved on your branch.

**Comment by linsen** [comment]
Dave's fix seems a good one :-)

**Comment by drubin** [comment]
I just tried creating a pull request but it doesn't seem to want to work will do it after the week end.
